### PR TITLE
Introduce configurable application label colors

### LINKED ISSUE #153: Extend colors in configuration service
The configuration service provides an interface to access and change landscape or application colors. However, there are properties missing for scene background color & label coloring for applications.
These properties should be added, used by e.g. the labeler and eventually also be configurable by the color picker extension.

### PR DESCRIPTION
**Pull request by malte-hansen**
Together with a major refactoring of the colorpicker extension (see branch dev-1) this pull request closes #153. 

**Frontend changes**
The frontend provides a service called _configuration.js_ which keeps track of the colors which should be applied to (almost) all drawn three.js objects. In detail, this service contains two main objects, namely _landscapeColors_ and _applicationColors_ which contain properties which determine the colors to be used for the rendering components. For example, the property _nodegroup_ of _landscapeColors_ can be set to "rgb(22, 158, 43)". Which colors are applied initially (without using the colorpicker extension) is determined by analog objects called _landscapeColorsDefault_ and _applicationColorsDefaul_t.

Issue #153 points out that properties for the label coloring of application entities (foundation, clazzes & components) were missing. Those properties were added and applied. Additionally, some existing property keys were renamed to increase readability for the colorpicker extension (see below). 

Lastly, a boolean property called _textChanged_ was part of _landscapeColors_ and was used to determine if the color of a label changed and thus a label needed to be recomputed. This property is obsolete for the current implementation, because the visualization and the colorpicker component are placed on different routes. Consequently, all labels are recomputed if the colorpicker component was used anyway. Additionally, by design the _textChanged_ property should not be part of the color properties.

**Colorpicker extension changes**
The colorpicker extension provides a component which allows users to change the color properties which are part of "configuration.js". In its original state, the colorpicker extension had code to initialize input fields and additionally add & remove listeners for them. Since there are a lot of properties this lead to several hundred lines of redundant code, both for the used component and template. 

Goal of the refactoring is, to reduce redundancy and keep the original functionality. Therefore, loop constructs are used which dynamically iterate through the properties of _landscapeColors_ and _applicationColors_ respectively. To make this work, the property names are also used for the template and thus are displayed to the user. The camelCase property names like "nodeText" are formatted to result in labels like "Node Text". This is why the naming and also the order of color properties matters for the colorpicker extension from now on.

As a result, in my book the colorpicker extension becomes much smaller and easier to understand. Redundancy is kept minimal and adding or changing properties to/of _landscapeColors_ or _applicationColors_ does not break the colorpicker extension. From now on it dynamically adapts to those changes just fine as long as the overall structure of _configuration.js_ stays the same.

### CODE REVIEW

**Review by Alexander-Krause-Glau — CHANGES_REQUESTED** [review]
Can you explain in this PR how the colorpicker now updates the colors of the core service? You did change a lot of code and I would like to keep the information in this PR. (Edit your initial post and eventually answer).

UPDATE: Can you additionally resolve the merge conflict that is due to the merge of another PR?

**Comment by malte-hansen** [comment]
@Alexander-Krause I merged dev-1 into this feature branch to resolve the merge confligt. Additionally, I updated my original post to reason about the commited changes. Let me know if some things are still unclear or if there are things about the implementation which need to be changed.

**Comment by malte-hansen** [comment]
After consulting @czirkelbach and to incorporate issue #33 into this pull request, the color scheme for visually impaired users was removed from _configuration.js_ and moved into the colorpicker extension.

**Review by Alexander-Krause-Glau — CHANGES_REQUESTED** [review]
@Malte-Hansen can you resolve the merge conflict and update the branch? I will then finally check this and hopefully merge both this branch and the dev-1 from the color-picker.

**Review by Alexander-Krause-Glau — APPROVED** [review]
Nice work.

**Pull request merged**
